### ISSUE TITLE
G_CD_NOISE cuts out after a second in SF64 (Workaround applied).

### ISSUE THREAD

**Issue by sonicdcer** [rt64/rt64#80]
It seems G_CD_NOISE only works for a second from being enabled by the game, it's kind of a pitty because RT64 seems to be the only HLE renderer that supports this and it actually looks good. It might have something to todo with the autodetection failing at some point, it usually lasts for one second.

**Comment by DarioSamo** [comment]
There's quite a few levels to this as it turns out.

There's no effect being missed in the rendering pipeline. All rectangles are processed as such.

It seems the game uses a rectangle to introduce noise that does not actually alter the framebuffer's contents at all (because it has zero intensity). RT64 is currently unable to emulate noise dithering without resorting to expensive GPU features that are out of the question for an HLE plugin, but the overall increase of brightness from its simulation of dithering is even worse in SF64 because of the VI Gamma mode being used amplifying the error to be much more visible.

I've pushed a workaround as an option that moves the center of the noise effect to be negative, which should lead to much better results on games that do this, but there's no objective answer as to how to apply this effect as long as it's impossible to emulate the 16-bit precision loss post-blend of noise dithering on color.

**Comment by DarioSamo** [comment]
Workaround has been merged.
